ERROR|20/May/2021 14:05:49|exception|946864|140432700581632|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|20/May/2021 14:27:56|log|946864|140432478566144|Internal Server Error: /access_token/
Traceback (most recent call last):
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/mobilitysqr_staging/mobility_apps/employee/views.py", line 1957, in post
    otp=User.objects.filter(otp=otp).values("id")
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/query.py", line 841, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/query.py", line 859, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/db/models/fields/__init__.py", line 1807, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'Kr@123'
ERROR|20/May/2021 14:27:56|basehttp|946864|140432478566144|"POST /access_token/ HTTP/1.1" 500 20503
ERROR|20/May/2021 17:57:18|exception|946864|140432706336512|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|21/May/2021 00:20:34|basehttp|946864|140432470173440|"GET /config/getuser?index=0 HTTP/1.1" 500 59
ERROR|21/May/2021 04:40:34|basehttp|946864|140432470173440|"GET /config/getuser?index=0 HTTP/1.1" 500 59
ERROR|21/May/2021 10:12:17|log|946864|140432714729216|Internal Server Error: /access_token/
Traceback (most recent call last):
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/generics.py", line 241, in get
    return self.list(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'access_token' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR|21/May/2021 10:12:17|basehttp|946864|140432714729216|"GET /access_token/ HTTP/1.1" 500 99100
ERROR|21/May/2021 10:14:02|log|946864|140432714729216|Internal Server Error: /Otp_Generate/
Traceback (most recent call last):
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/generics.py", line 241, in get
    return self.list(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/var/www/html/mobilitysqr_api/mobilitysqr_staging_virtualenv/lib64/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'Otp_Generate' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR|21/May/2021 10:14:02|basehttp|946864|140432714729216|"GET /Otp_Generate/ HTTP/1.1" 500 99100
