ERROR|25/Nov/2020 11:20:03|log|13823|139918449391360|Internal Server Error: /getassignmentletter/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqrapi/mobility_apps/letter/views.py", line 108, in get
    datas['AssignmentStartDate']=self.date_format(date=data['Actual_Start_Date'])
  File "/var/www/html/mobilitysqrapi/mobility_apps/letter/views.py", line 516, in date_format
    dt = datetime(str(date))
TypeError: an integer is required (got type str)
ERROR|25/Nov/2020 11:20:03|basehttp|13823|139918449391360|"GET /getassignmentletter/?travel_req_id=TR185141 HTTP/1.1" 500 17524
ERROR|25/Nov/2020 11:20:25|log|13823|139918449391360|Internal Server Error: /getassignmentletter/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqrapi/mobility_apps/letter/views.py", line 108, in get
    datas['AssignmentStartDate']=self.date_format(date=data['Actual_Start_Date'])
  File "/var/www/html/mobilitysqrapi/mobility_apps/letter/views.py", line 516, in date_format
    dt = datetime(str(date))
TypeError: an integer is required (got type str)
ERROR|25/Nov/2020 11:20:25|basehttp|13823|139918449391360|"GET /getassignmentletter/?travel_req_id=TR185141 HTTP/1.1" 500 17524
