ERROR|09/Feb/2021 11:26:21|log|4949|140506401781504|Internal Server Error: /getassignmentletter/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/letter/views.py", line 95, in get
    if data['emp_info']:
KeyError: 'emp_info'
ERROR|09/Feb/2021 11:26:21|basehttp|4949|140506401781504|"GET /getassignmentletter/?travel_req_id=TR652036 HTTP/1.1" 500 17293
ERROR|09/Feb/2021 11:27:01|log|4949|140506410174208|Internal Server Error: /getassignmentletter/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/letter/views.py", line 95, in get
    if data['emp_info']:
KeyError: 'emp_info'
ERROR|09/Feb/2021 11:27:01|basehttp|4949|140506410174208|"GET /getassignmentletter/?travel_req_id=TR652036 HTTP/1.1" 500 17294
ERROR|09/Feb/2021 11:28:28|exception|4949|140506410174208|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 12:28:59|exception|4949|140506164098816|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 12:29:30|exception|4949|140506164098816|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 13:53:19|log|4949|140506147313408|Internal Server Error: /users
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/middleware/common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/middleware/common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 52.165.220.40:8080/users/?page=&size=5 (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR|09/Feb/2021 13:53:19|basehttp|4949|140506147313408|"POST /users?page=&size=5 HTTP/1.1" 500 65328
ERROR|09/Feb/2021 14:01:26|exception|4949|140506147313408|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 15:53:19|exception|4949|140506382640896|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 15:58:59|basehttp|4949|140506147313408|You're accessing the development server over HTTPS, but it only supports HTTP.

ERROR|09/Feb/2021 16:35:15|exception|4949|140506382640896|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 16:40:48|exception|4949|140506382640896|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 17:33:16|exception|4949|140506142856960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 18:17:22|exception|4949|140506134464256|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 18:27:13|exception|4949|140506142856960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 19:54:27|exception|4949|140506142856960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 20:32:24|exception|4949|140506142856960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 22:11:27|exception|4949|140506142856960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 22:16:58|exception|4949|140506142856960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|09/Feb/2021 22:34:12|exception|4949|140506142856960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 00:02:46|exception|4949|140506382640896|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 03:55:15|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 05:35:26|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 05:36:27|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 05:39:52|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 05:49:37|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 06:38:37|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 06:58:28|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 07:06:02|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 07:16:40|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 07:45:16|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 07:52:46|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 07:52:46|basehttp|4949|140506159642368|"GET /script HTTP/1.1" 500 59
ERROR|10/Feb/2021 09:27:33|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 09:28:23|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 09:43:50|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 10:01:23|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 10:48:40|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 10:48:40|basehttp|4949|140506159642368|"GET /script HTTP/1.1" 500 59
ERROR|10/Feb/2021 10:50:00|exception|4949|140506151249664|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 12:11:06|exception|4949|140506134464256|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 12:11:06|basehttp|4949|140506134464256|"GET /manager/html HTTP/1.1" 500 59
ERROR|10/Feb/2021 13:39:52|exception|4949|140506151249664|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 13:49:53|exception|4949|140506151249664|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 15:14:21|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 16:09:00|exception|4949|140506382640896|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 16:25:23|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 17:13:10|basehttp|4949|140506382640896|"GET /media/Koala_74ufFrT.jpg HTTP/1.1" 500 59
ERROR|10/Feb/2021 17:21:15|log|4949|140506382640896|Internal Server Error: /emoloyeeinfo/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/employee/views.py", line 81, in post
    if employees[0]['active_start_date']:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
ERROR|10/Feb/2021 17:21:15|basehttp|4949|140506382640896|"POST /emoloyeeinfo/ HTTP/1.1" 500 17141
ERROR|10/Feb/2021 17:24:38|log|4949|140506382640896|Internal Server Error: /emoloyeeinfo/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/employee/views.py", line 81, in post
    if employees[0]['active_start_date']:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
ERROR|10/Feb/2021 17:24:38|basehttp|4949|140506382640896|"POST /emoloyeeinfo/ HTTP/1.1" 500 17141
ERROR|10/Feb/2021 17:40:16|exception|4949|140506151249664|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 18:15:04|exception|4949|140506117678848|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 19:26:14|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 19:26:14|basehttp|4949|140506126071552|"GET /manager/html HTTP/1.1" 500 59
ERROR|10/Feb/2021 20:45:56|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 21:12:49|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 21:12:49|basehttp|4949|140506126071552|"GET /script HTTP/1.1" 500 59
ERROR|10/Feb/2021 21:23:21|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 21:57:52|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 23:25:41|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 23:28:14|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 23:33:44|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|10/Feb/2021 23:56:23|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 00:05:02|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 00:35:52|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 01:07:24|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 01:13:05|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 03:04:38|exception|4949|140506134464256|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 03:21:04|exception|4949|140506134464256|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 04:29:26|basehttp|4949|140506134464256|You're accessing the development server over HTTPS, but it only supports HTTP.

ERROR|11/Feb/2021 04:32:41|basehttp|4949|140506134464256|You're accessing the development server over HTTPS, but it only supports HTTP.

ERROR|11/Feb/2021 07:14:14|exception|4949|140506134464256|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 07:22:36|exception|4949|140506134464256|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 08:19:28|exception|4949|140506134464256|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 10:12:15|log|4949|140506134464256|Internal Server Error: /users
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/middleware/common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/middleware/common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 52.165.220.40:8080/users/?page=&size=5 (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR|11/Feb/2021 10:12:15|basehttp|4949|140506134464256|"POST /users?page=&size=5 HTTP/1.1" 500 65330
ERROR|11/Feb/2021 15:04:39|exception|4949|140506117678848|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 16:06:04|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 17:34:22|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 19:16:06|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 20:19:40|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|11/Feb/2021 22:46:56|exception|4949|140506382640896|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|12/Feb/2021 01:08:43|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|12/Feb/2021 03:00:47|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|12/Feb/2021 03:52:28|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|12/Feb/2021 05:02:34|exception|4949|140506382640896|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|12/Feb/2021 13:01:55|exception|4949|140506117678848|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|12/Feb/2021 13:15:41|exception|4949|140506117678848|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|12/Feb/2021 14:07:03|exception|4949|140506126071552|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|12/Feb/2021 14:56:07|exception|4949|140506159642368|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|12/Feb/2021 16:24:01|basehttp|4949|140506159642368|You're accessing the development server over HTTPS, but it only supports HTTP.

ERROR|12/Feb/2021 16:55:46|basehttp|4949|140506159642368|You're accessing the development server over HTTPS, but it only supports HTTP.

