ERROR|25/Feb/2021 11:37:48|log|14095|140625098520320|Internal Server Error: /api/login
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/middleware/common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/middleware/common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR|25/Feb/2021 11:37:48|basehttp|14095|140625098520320|"POST /api/login HTTP/1.1" 500 71022
WARNING|25/Feb/2021 11:38:26|log|14095|140625098520320|Bad Request: /api/login/
WARNING|25/Feb/2021 11:38:26|basehttp|14095|140625098520320|"POST /api/login/ HTTP/1.1" 400 107
INFO|25/Feb/2021 11:38:52|basehttp|14095|140625098520320|"POST /api/login/ HTTP/1.1" 200 441
INFO|25/Feb/2021 15:27:32|autoreload|32734|140134933120768|Watching for file changes with StatReloader
INFO|25/Feb/2021 18:22:04|basehttp|28697|140609168557824|"POST /api/login/ HTTP/1.1" 200 441
INFO|25/Feb/2021 18:23:51|basehttp|28697|140609168557824|"POST /api/login/ HTTP/1.1" 200 441
INFO|25/Feb/2021 18:25:37|basehttp|29175|140503085696768|"POST /api/login/ HTTP/1.1" 200 441
